### ISSUE TITLE
Mapping missing roads in Ghana

### ISSUE THREAD

**Issue by vardzelyan** [bolteu/OSM_Mapping_at_Bolt#1]
**Task Description:**
This task outlines work to improve road network in Accra and Kumasi. We plan to add missing roads and road attributes.

**Mapping Guidelines:**
The team will follow the process described in our wikis: https://wiki.openstreetmap.org/wiki/Organised_Editing/Activites/Bolt and https://wiki.openstreetmap.org/wiki/Bolt alongside with OSM and local guidelines.

**Tools:**
The team will use JOSM for completing the task. JOSM has validation warnings for road networks and other possible issues that are important to prevent improper changes.

**Sources:**
The team will use the imagery and data sources as available, including:

- Bing sattelite imagery for aligning the offset
- Other available satellite imageries for visual validation of missing roads (Maxar, Esri)
- Public street-level imageries (Mapillary, Kartaview)

**Changeset Comments:**
`Mapping missing roads: https://github.com/bolteu/osm_mapping/issues/1`

**Error Detection:** 
The team will check for errors visually and using JOSM validation warnings prior to committing the changeset.

**Contributors:**
 [Bolt017](https://www.openstreetmap.org/user/Bolt017), [Bolt018](https://www.openstreetmap.org/user/Bolt018), [Bolt019](https://www.openstreetmap.org/user/Bolt019), [Bolt020](https://www.openstreetmap.org/user/Bolt020), [Bolt021](https://www.openstreetmap.org/user/Bolt022)

**Comment by ebube-tech** [comment]
Can I join this project?
